### PR TITLE
Added support for Google Image Sitemaps

### PR DESCRIPTION
**Pull request by mogren**
Added Images. http://support.google.com/webmasters/bin/answer.py?hl=en&answer=178636
There are only two tests so far.

### CODE REVIEW

**Comment by mogren** [comment]
I should probably update the html-documentation as well. Will fix.

**Comment by eric-brechemier** [comment]
Thanks for the pull request! I'm glad to see that you are also interested in this forked project.

Looking at the specification for image site maps, I was wondering how to choose a relevant HTML page (loc) to associate with images in generated site maps: it is hard to know in which page each image is actually used, and it may not be practical to repeat the image for each HTML page in which it appears anyway.

What is your take on this?

**Comment by eric-brechemier** [comment]
By the way, let me know when you are done and I will merge the pull request (any new commit pushed to your master branch will be included in this pull request before it gets closed).

**Comment by mogren** [comment]
Hi again, sorry for the slow updates. I've updated the documentation and version number. 

And just so you know, we have been using this code in production since January. Each night we generate new sitemaps with about 140.000 urls and 10.000 of them have images added. The performance is acceptable, taking about 15 minutes to generate and write to disk. You can take a look at the files here:  http://skolbanken.unikum.net/sitemap.xml

**Comment by eric-brechemier** [comment]
Nice work. Thanks for the update. The example in the documentation and the unit tests are particularly useful.

I am glad that the sitemap generation works smoothly beyond the threshold of 50,000 URLs, this is the feature which motivated this fork in the first place.

I am a little worried though by the lack of validation of the size of the sitemap (less than 10MB) in current SitemapValidator, with your sitemap2.xml getting close to this limit with 9,082,402 bytes (87% of 10,485,760 bytes). I will open two new issues: add validation of the size limit, break files before size limit during generation.

**Pull request merged**
